version: "3.8"

volumes:
  lenta_pg_data:
  lenta_static:

services:
  db: 
    image: postgres:15
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - lenta_pg_data:/var/lib/postgresql/data

  backend:
    image: anstane/lenta_backend
    env_file: .env
    restart: always
    volumes:
      - lenta_static:/backend_static
    command: /app/start_backend.sh
    depends_on:
      - db

  gateway:
    image: nginx:1.22.1
    env_file: .env
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - lenta_static:/staticfiles/
    ports:
      - 8000:80
